version: '3.8'
services:
  laravel_api:
    container_name: laravel_api
    build: ./api/
    volumes:
      - ./api:/var/www/html
    ports:
      - 8000:80
  frontend:
    container_name: frontend
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager_db
    ports:
    - 3306:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1