version: '3.8'
services:
  laravel_api:
    container_name: laravel_api
    build: ./api/
    volumes:
      - ./api:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - mynetwork
  frontend:
    container_name: frontend
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/var/www/html
    networks:
      - mynetwork
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
    - 3306:3306
    networks:
      - mynetwork
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge