import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { DarkModeSwitcher } from "@/components/DarkModeSwitcher";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <div className="max-w-xs">
            <DarkModeSwitcher />  
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
